### ISSUE TITLE
bug: getting errors with `search` and `find` methods

### ISSUE THREAD

**Issue by twilson63** [MetaweaveTeam/arweave-account#1]
when trying to `search` handle or `find` name, I continue to get the following error:

```
[chunk] Failed to fetch chunk at offset 61423396626679
[chunk] This could indicate that the chunk wasn't uploaded or hasn't yet seeded properly to a particular gatway/node
Uncaught Error: Coudn't complete data download at 0/120
    at Chunks.downloadChunkedData (/workspace/permanotes/app/node_modules/arweave/node/chunks.js:74:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transactions.getData (/workspace/permanotes/app/node_modules/arweave/node/transactions.js:141:22)
    at async REPL85:1:24
```

After a little research, I think this is possibly due to a bad transaction on arweave:

when I run the following GQL query

```
query {
  transactions(tags:{name:"handle", values:["rakis"]}) {
    edges {
      node {
        id
      }
    } 
  }
}
```

I get two identifiers: 1HfOBWt5brDNNIt96fIRazPOUOxAF-p8R5_YXXo9hN0, YRecidAYb-nlSW4rlRZlKzQ66qOhPrGvBMX8qLguHfE

The arweave.transactions.getData method works find for the first identifier but does not work well for the second. 

Looking at the code, I wonder if it might make sense to catch on transactions.getData method.

https://github.com/MetaweaveTeam/arweave-account/blob/main/src/index.ts#L60

``` js
const data = await this.arweave.transactions.getData(txid, { decode: true, string: true });
```

for

``` js
const data = await this.arweave.transactions.getData(txid, { decode: true, string: true })
  .catch(() => null)
```

there may be a better way, but the routine is error-ring out when I make the following call.

``` js
await arweaveAccount.search('rakis')
```

**Comment by twilson63** [comment]
happy to work on PR on this is it is ok with you

**Comment by twilson63** [comment]
If you would be open, I think changing 

``` js
const data = await this.arweave.api.get(txid)
```

Might fix this issue.

**Comment by cromatikap** [comment]
Hey hello!

I never faced this kind of error before and I cannot reproduce it.
I just tried to type `rakis` and I get:
```
[
  {
    "txid": "1HfOBWt5brDNNIt96fIRazPOUOxAF-p8R5_YXXo9hN0",
    "profile": {
      "addr": "vh-NTHVvlKZqRxc8LyyTNok65yQ55a_PJ1zWLb9G2JI",
      "links": {
        "twitter": "rakis_me",
        "github": "rakis-me"
      },
      "handle": "rakis#vh-2JI",
      "name": "rakis",
      "bio": "Arweave Developer",
      "avatar": "fYmFNZbRCbPhBWqmOJLNiJFoLFiFchIBSZNI6jRwWaI"
    }
  }
]
```

I pushed a commit to add caching and I cleaned up some details on the way, let me know if you have any trouble with `1.2.0`

-----

```
const data = await this.arweave.transactions.getData(txid, { decode: true, string: true })
  .catch(() => null)
```

That's a good idea IMHO

------

```
const data = await this.arweave.api.get(txid)
```

Yep let's have a try :)

Feel free to drop a PR 👍 
Thanks for helping! I appreciate

**Comment by twilson63** [comment]
Thank you for the response, the caching looks cool,

```
// doing assignment in conditional
if (cachedResult = cache.get) {

}
```

I have not seen that before, when would it not be truthy? If the conditional returns null or undefined?

As far as v1.2.0 - I gave it a try and continued to get the same error, the search via ardb finds two transactions, and it is able to get data of the first transaction but gets the error with the second (older) transaction. IDK, why it is clearly working for your application and not mine. 

I am going to work on PR

**Comment by cromatikap** [comment]
Hi, sorry for the delay. I got the same kind of error you had 1 time, after refreshing the app I didn't have it anymore. It is related to the gateway and seems to be out of our scope of action.

----

```
let cacheResponse;
if ((cacheResponse = this.cache.get(addr))) return cacheResponse;
```
is equivalent to
```
const cacheResponse = this.cache.get(addr);
if (cacheResponse) return cacheResponse;
```
The last one might be less confusing indeed.

> when would it not be truthy?

`cache.get()` returns `undefined` when the account is not cached or has expired.
