### ISSUE TITLE
Issues with the newest arweave-js version (1.13.5)

### ISSUE THREAD

**Issue by luckyr13** [MetaweaveTeam/arweave-account#15]
Hello Metaweave team!

Today I was updating the libs on some of my projects and noticed that `arweave-account` does not return the Account Profile Object in the newest version for the `arweave-js` library (version `1.13.5`).

It seems to work fine up to `arweave-js 1.13.4` but it somehow fails in `1.13.5` version.

I checked the `arweave-account` dependencies on the `package.json` file and noticed that is using:
 ```
"arweave": "^1.12.4"
```
The issue happens when I try to get a profile:
```js
const account = new Account(props);
const profile = await account.get(address);
```
I have checked the browser console and notice that it is getting the profile just fine:
```
data {handle: 'luckyr13', avatar: 'ar://ZgeR31UrhBXIBAftcEPcIoW8zLNDIZm8hZhtTFbDQSY', banner: 'ar://a0ieiziq2JkYhWamlrUCHxrGYnHWUAMcONxRmfkWt-k', links: {…}, wallets: {…}}
```
But somehow the `account.get` method is always returning the defaultAccount object. I think that the problem is related to this line: https://github.com/MetaweaveTeam/arweave-account/blob/main/src/index.ts#L111

```js
try {
  const accountObj = this.data.decode(txid, addr, JSON.parse(data));
  this.cache?.hydrate(addr, accountObj);
  return accountObj;
} catch (e) {
  // if JSON.parse(data) throw an error because data is not a valid JSON
  return this.data.getDefaultAccount(addr);
}
```

Do you think that it would be possible to update `arweave-account` to work with the latest version of `arweave-js`? I think that could help to solve the problem.

🙏Thanks in advance and great job creating this awesome library, I really love using `arweave-account` in my projects.

**Comment by jessopb** [comment]
Reproducing with cache=false,
It seems like as long as either     
"arweave": "1.13.4",
or
"arweave-account": "1.3.4",
are set, it returns the proper profile object.
But advancing both beyond .4 causes it to fail.

**Comment by cromatikap** [comment]
Hi all, thanks for the good words.
The latest `arweave-account` [v1.4.0](https://www.npmjs.com/package/arweave-account) is using `arweave` v1.14.0 and I tested the good functioning of it 👍
