### ISSUE TITLE
chg(update): Add Optional Tags Argument to updateProfile

### ISSUE THREAD

**Issue by twilson63** [MetaweaveTeam/arweave-account#17]
Proposal to add an optional tags argument to the update profile. This argument will let app developers attach extra tags to the the ArProfile, for example they could attach ANS-110 

https://specs.g8way.io/?tx=SYHBhGAmBo6fgAkINNoRtumOzxNB8-JFv2tPhBuNk5c

Or even a [Stampable Asset](https://specs.g8way.io/#/view/y_ykD1T51BAM1Q2PrJK5bjZt9gf53EFMBW8nv3ooHj4) to the profile, which could allow the owner to earn stamp rewards for users that stamped the profile.

Tags to register any TX as a STAMP able asset.

```js
[
{name: "App-Name", value: "SmartWeaveAction"},
{name: "App-Version", value: "0.3.0"},
{name: "Contract", value: "TlqASNDLA1Uh8yFiH-BzR_1FDag4s735F3PoUFEv2Mo"},
{name: "Input", value: JSON.stringify({ function: "register"}) }
]
```

**Comment by cromatikap** [comment]
Good idea! Thanks!
Added in [v1.4.1](https://www.npmjs.com/package/arweave-account)
